# Generated by Django 5.0.6 on 2024-12-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JDC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='day_of_week',
            field=models.CharField(choices=[('Segunda', 'Segunda')], max_length=10, null=True),
        ),
    ]
