# Generated by Django 5.0.6 on 2024-12-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JDC', '0005_rename_book_treinos_alimentacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimentacao',
            old_name='jantae',
            new_name='almoço1',
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='almoço2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='almoço3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='almoço4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='almoço5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='almoço6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='day_of_week1',
            field=models.CharField(choices=[('Terça', 'Terça')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='day_of_week2',
            field=models.CharField(choices=[('Quarta', 'Quarta')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='day_of_week3',
            field=models.CharField(choices=[('Quinta', 'Quinta')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='day_of_week4',
            field=models.CharField(choices=[('Sexta', 'Sexta')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='day_of_week5',
            field=models.CharField(choices=[('Sabado', 'Sabado')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='day_of_week6',
            field=models.CharField(choices=[('Domingo', 'Domingo')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='jantae2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='jantae3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='jantae4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='jantae5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='jantae6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='jantar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='jantar1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='peqno_almoço1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='peqno_almoço2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='peqno_almoço3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='peqno_almoço4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='peqno_almoço5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='peqno_almoço6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alimentacao',
            name='day_of_week',
            field=models.CharField(choices=[('Segunda', 'Segunda')], max_length=10, null=True),
        ),
    ]
