# Generated by Django 5.0.6 on 2024-12-27 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JDC', '0007_rename_jantae2_alimentacao_jantar2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnése',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Idade', models.IntegerField()),
                ('Género', models.CharField(choices=[('Másculino', 'Másculino'), ('Feminino', 'Feminino')], max_length=10, null=True)),
                ('Trabalho', models.CharField(choices=[('Sentado', 'Sentado'), ('Físico', 'Físico')], max_length=10, null=True)),
                ('Horas_de_Trabalho', models.IntegerField()),
                ('Prt_actividade_fis', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True)),
                ('Peso', models.IntegerField()),
                ('Objectivo', models.CharField(choices=[('Ganhar', 'Ganhar'), ('Perder', 'Perder')], max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
