# Generated by Django 5.0.6 on 2024-12-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JDC', '0008_anamnése'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnése',
            name='Género',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10, null=True),
        ),
    ]
