# Generated by Django 5.0.6 on 2025-01-06 08:36

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JDC', '0017_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnése',
            name='Altura',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='anamnése',
            name='Percetual_de_gordura',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anamnése',
            name='Objectivo',
            field=models.CharField(choices=[('Ganhar', 'Ganhar'), ('Perder', 'Perder'), ('Manter', 'Manter')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
