# Generated by Django 5.0.6 on 2025-01-06 09:05

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JDC', '0018_anamnése_altura_anamnése_percetual_de_gordura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnése',
            name='Gordura_visceral',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
